---
apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    name: postgress-pod
    app: voting-app
spec:
  containers:
    - name: postgress-pod
      image: postgres:9.4
      env:
      - name: POSTGRES_USER
        value: "postgres"
      - name:  POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust
      ports:
        - containerPort: 5432