---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-pod-deployment
  labels:
    name: voting-pod-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app-pod
      app: voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: voting-app

    spec:
      containers:
        - name: voting-app-pod
          image: dockersamples/examplevotingapp_vote
          ports:
          - containerPort: 80
    