---
apiVersion: v1
kind: Service
metadata:
  name: mynewproject1-clusterip
  labels:
    app: shop
    env: lab
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shop