---
apiVersion: v1
kind: Service
metadata:
  name: mynewproject1
  labels:
    app: shop
    env: lab
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shop