apiVersion: apps/v1
kind: Deployment
metadata:
  name: newproject
  labels:
    app: shop
    env: lab

spec:
  selector:
    matchLabels:
      app: shop
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0     
  template:
    metadata:
      name: myproject1
      labels:
          app: shop
          env: lab
          version: newversion
    spec:
      containers:
        - name: myproject1cont
          image: tomcat
      
    