apiVersion: apps/v1
kind: Deployment
metadata:
  name: newproject
  labels:
    app: shop
    env: lab

spec:
  selector:
    matchLabels:
      app: shop
  replicas: 2
  template:
    metadata:
      name: myproject1
      labels:
          app: shop
          env: lab
    spec:
      containers:
        - name: myproject1cont
          image: sathya240/sathyapragada:myapp
      
    