---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: project
  labels:
    app: my_project
    env: lab
spec:
  selector:
    matchLabels:
      app: project
  replicas: 3
  template:
    metadata:
      name: myproject1
      labels:
        app: project
        env: lab
    spec:
      containers:
        - name: myproject1cont
          image: nginx